# fly.toml app configuration file generated for patient-shape-7051 on 2023-08-25T12:30:43+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patient-shape-7051"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
